version: '3.9'

services:
  app:
    ports:
      - "48000:45000"
    command:
      - --host=0.0.0.0
      - --port=45000
    volumes:
      - ./db:/wd/db:rw
    user: "${UID}"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0


