version: '3.9'

services:
  app:
    ports:
      - "48000:48000"
    command:
      - --host=0.0.0.0
    volumes:
      - ./db:/wd/db:rw
    user: "${UID}"
    environment:
      - FLASK_APP=main.py
