version: '3.9'

services:
  app:
    ports:
      - "48000:45000"
    command:
      - --host=0.0.0.0
    volumes:
      - ./db/db_hw15.db:/wd/db/db_hw15.db:rw
    user: "${UID}"
    environment:
      - FLASK_APP=main.py
